sudo: required
dist: trusty

language: csharp
mono:
  - latest

addons:
  apt:
    packages:
    - gettext
    - libunwind8
    - libicu52
    - dbus

branches:
  only:
    - coreclr

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get -y install dotnet-dev-1.0.0-preview4-004233

script:
  - ./build.sh Build
  - ./build.sh RunTests
 