version: 2.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
branches:
  only:
  - coreclr
install:
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath -Version 1.0.0-preview4-004233' 
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
build_script:
- cmd: build.cmd Build
test_script:
- cmd: build.cmd RunTests
- cmd: build.cmd CreateNuget
artifacts:
- path: bin\nuget\*.nupkg
  name: nuget
- path: TestResults\
  name: test
deploy:
- provider: NuGet
  server: https://www.myget.org/F/akka-netcore/api/v2
  on:
    branch: coreclr
  api_key:
    secure: oC2sjz2Dnd7PM0eRLdwhZbOH6y06PLf9Pb9HYv4ujm/fRxgGw3KWZ3mtxmnHt+zv
  skip_symbols: true